Controllers/AddFoodController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using Sushi.Data;
using Sushi.Data.Models;
using System.Linq;
using System.Threading.Tasks;
using System.Xml.Linq;

namespace Sushi.Controllers
{
    public class AddFoodController : Controller
    {

        private readonly appDBContent _appDBContent;

        public AddFoodController(appDBContent appDBContent)
        {
            _appDBContent = appDBContent;
        }

        public IActionResult Index()
        {
            return View(_appDBContent.Food.ToList());
        }
        public IActionResult AddNewFood()
        {
            return View();
        }
        [HttpPost]
        public IActionResult AddNewFood(Food food)
        {
            _appDBContent.Food.Add(food);
            _appDBContent.SaveChanges();
            return RedirectToAction("Index", "Offert");
        }
        [HttpPost]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id != null)
            {
                Food food = await _appDBContent.Food.FirstOrDefaultAsync(p => p.Id == id);
                if (food != null)
                {
                    _appDBContent.Food.Remove(food);
                    await _appDBContent.SaveChangesAsync();
                    return RedirectToAction("Index", "Offert");
                }
            }
            return NotFound();
        }
        public async Task<IActionResult> Edit(int? id)
        {
            if (id != null)
            {
                Food food = await _appDBContent.Food.FirstOrDefaultAsync(p => p.Id == id);
                if (food != null) return View(food);
            }
            return NotFound();
        }
        [HttpPost]
        public async Task<IActionResult> Edit(Food food)
        {
            _appDBContent.Food.Update(food);
            await _appDBContent.SaveChangesAsync();
            return RedirectToAction("Index", "Offert");
        }
    }
}

Controllers/ShopCartController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Sushi.Data;
using Sushi.Data.Interfaces;
using Sushi.Data.Models;
using Sushi.ViewModels;
using System.Linq;
using System.Threading.Tasks;

namespace Sushi.Controllers
{
    public class ShopCartController : Controller
    {
        private readonly IAllFood _foodRepository;
        private readonly ShopCart _shopCart;
        private readonly appDBContent _appDBcontent;
        public ShopCartController(IAllFood foodRep, ShopCart shopCart)
        {
            _foodRepository = foodRep;
            _shopCart = shopCart;
        }

        public ViewResult Index()// данная функция будет позвоолять нам вызвать определенный html шаблон
        {
            var items = _shopCart.GetShopItems();
            _shopCart.ListShopItems = items;

            var obj = new ShopCartViewModel
            {
                shopCart = _shopCart
            };

            return View(obj);
        }

        public RedirectToActionResult addToCart(int id) 
        {
           
            var item = _foodRepository.Food.FirstOrDefault(x => x.Id == id);
            if (item != null)
            {
                _shopCart.AddToCart(item);
            }
            return RedirectToAction("Index"); 
        }
        [HttpPost]
        public RedirectToActionResult Delete(int id)
        {
            if (id != null)
            {
                _shopCart.RemoveFromCart(id);
            }

            return RedirectToAction("Index");
        }
    }
}

Controllers/UsersController.cs

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Sushi.Data.Models;
using Sushi.ViewModels;
using System.Linq;
using System.Threading.Tasks;

namespace Sushi.Controllers
{
    [Authorize(Roles = "admin")]
    public class UsersController : Controller
    {
        private readonly UserManager<User> _userManager;

        public UsersController(UserManager<User> userManager)
        {
            _userManager = userManager;
        }

        public IActionResult Index() => View(_userManager.Users.ToList());

        public IActionResult Create() => View();

        [HttpPost]
        public async Task<IActionResult> Create(CreateUserViewModel model)
        {
            if (ModelState.IsValid)
            {
                User user = new User { Email = model.Email, UserName = model.Email, Year = model.Year };
                var result = await _userManager.CreateAsync(user, model.Password);
                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    foreach (var error in result.Errors)
                    {
                        ModelState.AddModelError(string.Empty, error.Description);
                    }
                }
            }
            return View(model);
        }

        public async Task<IActionResult> Edit(string id)
        {
            User user = await _userManager.FindByIdAsync(id);
            if (user == null)
            {
                return NotFound();
            }
            EditUserViewModel model = new EditUserViewModel { Id = user.Id, Email = user.Email, Year = user.Year };
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(EditUserViewModel model)
        {
            if (ModelState.IsValid)
            {
                User user = await _userManager.FindByIdAsync(model.Id);
                if (user != null)
                {
                    user.Email = model.Email;
                    user.UserName = model.Email;
                    user.Year = model.Year;

                    var result = await _userManager.UpdateAsync(user);
                    if (result.Succeeded)
                    {
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        foreach (var error in result.Errors)
                        {
                            ModelState.AddModelError(string.Empty, error.Description);
                        }
                    }
                }
            }
            return View(model);
        }

        [HttpPost]
        public async Task<ActionResult> Delete(string id)
        {
            User user = await _userManager.FindByIdAsync(id);
            if (user != null)
            {
                IdentityResult result = await _userManager.DeleteAsync(user);
            }
            return RedirectToAction("Index");
        }
        public async Task<IActionResult> ChangePassword(string id)
        {
            User user = await _userManager.FindByIdAsync(id);
            if (user == null)
            {
                return NotFound();
            }
            ChangePasswordViewModel model = new ChangePasswordViewModel { Id = user.Id, Email = user.Email };
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> ChangePassword(ChangePasswordViewModel model)
        {
            if (ModelState.IsValid)
            {
                User user = await _userManager.FindByIdAsync(model.Id);
                if (user != null)
                {
                    var _passwordValidator =
                        HttpContext.RequestServices.GetService(typeof(IPasswordValidator<User>)) as IPasswordValidator<User>;
                    var _passwordHasher =
                        HttpContext.RequestServices.GetService(typeof(IPasswordHasher<User>)) as IPasswordHasher<User>;

                    IdentityResult result =
                        await _passwordValidator.ValidateAsync(_userManager, user, model.NewPassword);
                    if (result.Succeeded)
                    {
                        user.PasswordHash = _passwordHasher.HashPassword(user, model.NewPassword);
                        await _userManager.UpdateAsync(user);
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        foreach (var error in result.Errors)
                        {
                            ModelState.AddModelError(string.Empty, error.Description);
                        }
                    }
                }
                else
                {
                    ModelState.AddModelError(string.Empty, "Пользователь не найден");
                }
            }
            return View(model);
        }
    }
}

Views/Shared/AddNewFood.cshtml
@{
    ViewBag.Title = "Добавить товар на сайт";
}
@model Food
<h2>Добавление нового товара</h2>
<form asp-action="AddNewFood" asp-controller="AddFood">
    <p>
        <label asp-for="Name">Наименование</label><br />
        <input type="text" asp-for="Name" />
    </p>
    <p>
        <label asp-for="Description">Описание</label><br />
        <input type="text" asp-for="Description" />
    </p>
    <p>
        <label asp-for="Category">Выберите категорию</label><br />
        <select asp-for="Category.Name">
            <option value="Пицца">Пицца</option>
            <option value="WOK">WOK</option>
            <option value="Роллы">Роллы</option>
            <option value="Салаты">Салаты</option>
            <option value="Напитки">Напитки</option>
        </select>
    </p>
    <p>
        <label asp-for="Price">Цена</label><br />
        <input type="number" asp-for="Price" />
    </p>
    <p>
        <label asp-for="Img">Путь к изображению /img/...</label><br />
        <input type="text" asp-for="Img" />
    </p>
    <p>
        <label asp-for="ToViewHome">Показать в рекомендациях?</label><br />
        <input type="checkbox" asp-for="ToViewHome" />
    </p>
    <p>
        <input type="submit" value="Добавить" />
    </p>
</form>
<form method="post" asp-controller="Users" asp-action="Index">
    <input type="submit" value="Пользователи" class="btn btn-warning" />
</form>

</td>

Views/Shared/Contacts.cshtml
@{
    ViewBag.Title = "Contacts";
}

<h2>Контакты</h2>

<div class="col-sm-3 col-xs-12">
    <ul class="list-unstyled">
        <li><a href="tel: +7 (983) 208-88-07">Телефон: <i class="fa fa-phone" style="margin-right: 5px; font-size: 16px"></i>533 27-4-27</a></li>
        <li><a><i class="fa fa-map-marker" style="margin-right: 5px; font-size: 16px"></i>г. Тирасполь</a></li>
        <li><a><i class="fa fa-map-marker" style="margin-right: 5px; font-size: 16px"></i>Ул. Покровская, 218</a></li>
        <li><a>E-mail: </a><a href="#">sushi.md@mail.com</a></li>
    </ul>
</div>

Views/Shared/Edit.cshtml
@model Food

<h2>Редактирование товара</h2>
<form asp-controller="AddFood" asp-action="Edit" method="post">
<div asp-validation-summary="All" class="text-danger"></div>
<div class="form-group">
    <input type="hidden" asp-for="Id" />
</div>
<div class="form-group">
    <label asp-for="Name" class="control-label">Наименование</label>
    <input type="text" asp-for="Name" class="form-control" />
</div>
<div class="form-group">
    <label asp-for="Description" class="control-label">Описание</label>
    <input type="text" asp-for="Description" class="form-control" />
</div>
<div>
    <label asp-for="Category">Выберите категорию</label><br />
    <select asp-for="Category.Name">
        <option value="Пицца">Пицца</option>
        <option value="WOK">WOK</option>
        <option value="Роллы">Роллы</option>
        <option value="Салаты">Салаты</option>
        <option value="Напитки">Напитки</option>
    </select>
</div>
<div class="form-group">
    <label asp-for="Price" class="control-label">Цена</label>
    <input type="number" asp-for="Price" class="form-control" />
</div>
<div class="form-group">
    <label asp-for="Img" class="control-label">Путь к изобоажению</label>
    <input type="text" asp-for="Img" class="form-control" />
</div>
<div>
    <label asp-for="ToViewHome">Показать в рекомендациях?</label><br />
    <input type="checkbox" asp-for="ToViewHome" />
</div>
<div class="form-group">
    <input type="submit" value="Сохранить" class="btn btn-outline-secondary" />
</div>
</form>

Views/Shared/Foods.cshtml
@model Food
@using Microsoft.AspNetCore.Identity
@inject UserManager<User> UserManage
@{
    var isAdmin = User.IsInRole("admin");
}

<div class="col-lg-3">
    <img class="img-thumbnail" src="@Model.Img" alt="@Model.Name" />
    <h2>@Model.Name</h2>
    <p>@Model.Description</p>
    <p>Цена: @Model.Price.ToString("c")</p>
    <p><a class="btn btn-warning" asp-controller="ShopCart" asp-action="addToCart" asp-route-Id="@Model.Id">B корзину</a></p>
    @if (isAdmin)
    {
        <a class="btn btn-primary mr-2" asp-controller="AddFood" asp-action="Edit" asp-route-id="@Model.Id">Изменить</a>
        <form asp-controller="AddFood" asp-action="Delete" method="post" asp-route-id="@Model.Id" style="display: inline;">
            <input type="submit" value="Удалить" class="btn btn-danger" />
        </form>
    }
</div>

Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject UserManager<User> UserManage
@{
    var isAdmin = User.IsInRole("admin");
    var isUser = User.IsInRole("user");
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" href="~/css/bootstrap.min.css" type="text/css" />
</head>
<body>
    <header>
        <div class="px-3 py-2 text-bg-dark border-bottom">
            <div class="container">
                <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
                    <a href="/" class="d-flex align-items-center my-2 my-lg-0 me-lg-auto text-white text-decoration-none">
                        <svg class="bi me-2" width="40" height="32" role="img" aria-label="Bootstrap"><use xlink:href="#bootstrap"></use></svg>
                    </a>

                    <ul class="nav col-12 col-lg-auto my-2 justify-content-center my-md-0 text-small">
                        <li>
                            <a href="/Offert/Index" class="nav-link text-white">
                                <svg class="bi d-block mx-auto mb-1" width="24" height="24"><use xlink:href="#grid"></use></svg>
                                Главная
                            </a>
                        </li>
                        <li>
                            <a href="/ShopCart/Index" class="nav-link text-white">
                                <svg class="bi d-block mx-auto mb-1" width="24" height="24"><use xlink:href="#table"></use></svg>
                                Корзина
                            </a>
                        </li>
                        <li>
                            <a href="/Home/Contacts" class="nav-link text-white">
                                <svg class="bi d-block mx-auto mb-1" width="24" height="24"><use xlink:href="#grid"></use></svg>
                                Контакты
                            </a>
                        </li>
                    </ul>
                    <ul class="nav col-12 col-lg-auto my-2 justify-content-center my-md-0 text-small">
                            @if (User.Identity.IsAuthenticated)
                            {
                            <li>
                                <p style="margin-right: 15px; margin-top: 30px; color: slateblue;">@User.Identity.Name</p>
                            </li>
                            <li>
                                <form method="post" asp-controller="Account" asp-action="Logout">
                                    <input type="submit" value="Выход" style="display: inline; margin-top: 30px;" />
                                </form>
                            </li>

                                @if (isAdmin)
                                {
                                <li>
                                    <a href="/AddFood/AddNewFood" class="nav-link text-white">
                                        <svg class="bi d-block mx-auto mb-1" width="24" height="24"><use xlink:href="#grid"></use></svg>
                                        Управление
                                    </a>
                                </li>
                                <li>
                                    <a href="/ViewOrder/OrderDetails" class="nav-link text-white">
                                        <svg class="bi d-block mx-auto mb-1" width="24" height="24"><use xlink:href="#grid"></use></svg>
                                        Заказы
                                    </a>
                                </li>
                                }
                            }
                            else
                            {
                            <a asp-controller="Account" asp-action="Login" style="margin-right: 10px;">Вход</a>
                            <a asp-controller="Account" asp-action="Register">Регистрация</a>
                            }
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </header>

    <div class="col-lg-6 px-0" style="width: 100vw;">
        <img src="~/img/bannera.jpg" alt="banner" style="width: 100%; height: auto; display: block;">
    </div>


    <div class="owl-controls clickable"><div class="owl-pagination"><div class="owl-page"><span class=""></span></div><div class="owl-page"><span class=""></span></div><div class="owl-page"><span class=""></span></div><div class="owl-page active"><span class=""></span></div><div class="owl-page"><span class=""></span></div></div></div>
    </div>
    <nav class="navbar navbar-expand-md bg-dark sticky-top border-bottom" data-bs-theme="dark">
        <div class="container">
            <a class="navbar-brand d-md-none" href="#">
                <svg class="bi" width="24" height="24"><use xlink:href="#aperture"></use></svg>
                Aperture
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvas" aria-controls="offcanvas" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="offcanvas offcanvas-end" tabindex="-1" id="offcanvas" aria-labelledby="offcanvasLabel">
                <div class="offcanvas-header">
                    <h5 class="offcanvas-title" id="offcanvasLabel">Aperture</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
                </div>
                <div class="offcanvas-body">
                    <ul class="navbar-nav flex-grow-1 justify-content-between">
                        <li class="nav-item">
                            <a class="nav-link" href="#">
                                <svg class="bi" width="24" height="24"><use xlink:href="#aperture"></use></svg>
                            </a>
                        </li>
                        <li class="nav-item"><a class="nav-link" href="/Home/List/pizza">Пицца</a></li>
                        <li class="nav-item"><a class="nav-link" href="/Home/List/rolls">Холодные роллы</a></li>
                        <li class="nav-item"><a class="nav-link" href="/Home/List/salad">Салаты</a></li>
                        <li class="nav-item"><a class="nav-link" href="/Home/List/drink">Напитки</a></li>
                        <li class="nav-item"><a class="nav-link" href="/Home/List/WOK">WOK</a></li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">
                                <svg class="bi" width="24" height="24"><use xlink:href="#cart"></use></svg>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </nav>

    <div class="container mt-5">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="container">
        <p class="float-end"><a href="#">Back to top</a></p>
        <p>© 2024 Все права защищены</p>


    </footer>
    <script src="~/js/bootstrap.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>