Controllers/OffertController.cs
using Microsoft.AspNetCore.Mvc;
using Sushi.Data.Interfaces;
using Sushi.ViewModels;

namespace Sushi.Controllers
{
    public class OffertController : Controller
    {
        private readonly IAllFood _foodRepository;

        public OffertController(IAllFood foodRep)
        {
            _foodRepository = foodRep;
        }

        public ViewResult Index()
        {
            var homeFoods = new OffertViewModel
            {
                FavFoods = _foodRepository.GetViewFoods
            };

            return View(homeFoods);
        }

        public ViewResult Cabin()
        {
            return View();
        }
    }
}

Controllers/OrderController.cs
using Microsoft.AspNetCore.Mvc;
using Sushi.Data.Models;
using Sushi.Data.Interfaces;
using MimeKit;
using MailKit.Net.Smtp;
using Sushi.ViewModels;
using System.Collections.Generic;
using System.Text;
using MailKit.Search;
using Org.BouncyCastle.Asn1.X509;
using Sushi.Data;
using Microsoft.EntityFrameworkCore;
using System.Threading.Tasks;
using System.Linq;
using static System.Net.Mime.MediaTypeNames;

namespace WebApplication1.Controllers
{
    public class OrderController : Controller
    {
        private readonly IAllOrders allOrders;
        private readonly ShopCart shopCart;
        private readonly appDBContent _appDBContent;

        public OrderController(IAllOrders allOrders, ShopCart shopCart, appDBContent appDBContent)
        {
            this.allOrders = allOrders;
            this.shopCart = shopCart;
            _appDBContent = appDBContent;
        }

        public IActionResult Checkout()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Checkout(Order order)
        {
            shopCart.ListShopItems = shopCart.GetShopItems();

            if (shopCart.ListShopItems.Count == 0)
            {
                ModelState.AddModelError("", "В корзине нет товаров!");
            }

            if (ModelState.IsValid)
            {
                allOrders.CreateOrder(order);
                return RedirectToAction("Complete", new { email = order.Email });
            }

            return View(order);
        }

        private string GenerateOrderEmailBody(IEnumerable<ViewOrderViewModel> orders)
        {
            var stringBuilder = new StringBuilder();

            stringBuilder.AppendLine("Ваш заказ!");

            foreach (var order in orders)
            {
                stringBuilder.AppendLine($"Время: {order.OrderTime}");
                stringBuilder.AppendLine($"Клиент: {order.Name}");
                stringBuilder.AppendLine($"Адрес: {order.Adress}");
                stringBuilder.AppendLine(" ");
                stringBuilder.AppendLine("Детали: ");

                uint sumProd = 0;
                foreach (var item in order.OrderDetails)
                {
                    stringBuilder.AppendLine($"{item.FoodName} - {item.Price.ToString("c")}");
                    sumProd += item.Price;
                }

                stringBuilder.AppendLine(" ");
                stringBuilder.AppendLine($"Итого: {sumProd.ToString("c")}");
            }

            return stringBuilder.ToString();
        }

        public async Task<IActionResult> Complete(string email)
        {
            var order = await _appDBContent.Order
                .Include(o => o.OrderDetails)
                .ThenInclude(od => od.Food)
                .FirstOrDefaultAsync(o => o.Email == email);

            var emailBody = GenerateOrderEmailBody(new List<ViewOrderViewModel>
            {
                new ViewOrderViewModel
                {
                    OrderId = order.OrderId,
                    OrderTime = order.OrderTime,
                    Name = order.Name,
                    Adress = order.Adress,
                    OrderDetails = order.OrderDetails.Select(d => new OrderDetailViewModel
                    {
                        FoodName = d.Food.Name,
                        Price = d.Price
                    }).ToList()
                }
            });


            var message = new MimeMessage();

            message.From.Add(new MailboxAddress("Информация о заказе", "wania1999@yahoo.com"));

            message.To.Add(new MailboxAddress(order.Name, order.Email));

            message.Subject = "Спасибо за заказ!";

            message.Body = new TextPart("plain")

            {

                Text = emailBody

            };

            using (var client = new SmtpClient())

            {


                client.Connect("smtp.mail.yahoo.com", 587, false);

                client.Authenticate("wania1999@yahoo.com", "cdkbqnzkfeikjowd");

                client.Send(message);

                client.Disconnect(true);

            }
            ViewBag.Message = "Заказ успешно обработан!";
            return View();
        }
        
    }
}

Views/Order/Checkout.cshtml
@using Sushi.Data.Models

@model Order

<div class="row">
    <h3>Оформление заказа</h3>
    <form asp-action="Checkout" method="post" class="form-group">
        <div class="form-group">
            <label asp-for="Name"></label>
            <div class="col-md-5">
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
        </div>

        <div class="form-group">
            <label asp-for="Adress"></label>
            <div class="col-md-5">
                <input asp-for="Adress" class="form-control" />
                <span asp-validation-for="Adress" class="text-danger"></span>
            </div>
        </div>

        <div class="form-group">
            <label asp-for="Phone"></label>
            <div class="col-md-5">
                <input asp-for="Phone" class="form-control" />
                <span asp-validation-for="Phone" class="text-danger"></span>
            </div>
        </div>

        <div class="form-group">
            <label asp-for="Email"></label>
            <div class="col-md-5">
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
        </div>
        <input class="btn btn-success" type="submit" value="Завершить заказ"/>
    </form>
</div>

Views/Order/Complete.cshtml
<h3>@ViewBag.Message</h3>
<a class="btn btn-primary mr-2" asp-controller="Offert" asp-action="Index">На главную!</a>

Views/Order/Mail.cshtml
<h3>@ViewBag.Message</h3>